server:
  port: 8080
  address: localhost
  servlet:
    contexgitt-path: /
spring:
  datasource:
      url: jdbc:mysql://118.25.40.127:3306/yfc
      username: root
      password: root17621053900
      driverClassName: com.mysql.jdbc.Driver
      type: org.apache.tomcat.jdbc.pool.DataSource
