server:
  port: 8080
  address: localhost
  servlet:
    contexgitt-path: /
spring:
  datasource:
    url: jdbc:mysql://118.25.40.127:3306/yfc
    username: root
    password: root17621053900
    driverClassName: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource



mybatis:
  #配置mapper.xml文件映射
  mapper-locations: classpath:mapper/*.xml
  #配置映射类所在包命
type-aliases-package: com.example.entity